apiVersion: v1
kind: Namespace
metadata:
  name: struts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts
  namespace: struts
  labels:
    app: struts
spec:
  #podAntiAffinity:
    #requiredDuringSchedulingIgnoredDuringExecution:
   # - labelSelector:
    #    matchExpressions:
   #     - key: app
  #        operator: In
 #         values:
 #         - struts
#      topologyKey: "kubernetes.io/hostname"
  replicas: 1
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
      - name: struts
        image: reyl/struts:0.1
        ports:
        - containerPort: 8080
#        resources:
#          limits:
#            cpu: 500m
#          requests:
#            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: struts
  namespace: struts
spec:
  type: NodePort
  selector:
    app: struts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: struts
#  namespace: struts
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: struts
#  minReplicas: 1
#  maxReplicas: 3
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50
